version: '3.7'

networks:
  api:
    driver: bridge

services:
    db:
      container_name: ${ENV_PREFIX}db
      build:
         context: ./db
         dockerfile: Dockerfile
      ports:
        - "1433:1433"
      environment:
        - ACCEPT_EULA="Y"
        - SA_PASSWORD=${SQL_SERVER_PASSWORD}
      networks:
        - api

    api:
      container_name: ${ENV_PREFIX}inventoryapp-api
      build:
         context: ./InventoryAppBack
         dockerfile: Dockerfile
      ports:
        - "5005:5005"
      #environment:
      #  - ASPNETCORE_URLS=http://+:5005
      #  - ASPNETCORE_ENVIRONMENT=Development
      depends_on:
        - db
      env_file:
        - "production.env"
      networks:
        - api
      
    front:
      container_name: ${ENV_PREFIX}inventoryapp-front
      build:
         context: ./InventoryAppFront
         dockerfile: Dockerfile
      ports:
        - "80:80"
      